// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgxHTukYW1LERTSYd3No0-MI-AegKhYU',
    appId: '1:631248749521:web:4281f2cf8cb5d8246396f0',
    messagingSenderId: '631248749521',
    projectId: 'codehub-bc560',
    authDomain: 'codehub-bc560.firebaseapp.com',
    storageBucket: 'codehub-bc560.appspot.com',
    measurementId: 'G-997R6248NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L9Nbia4UCzItCodKxDDTe2M1U5IMtBc',
    appId: '1:631248749521:android:b899a2067823be956396f0',
    messagingSenderId: '631248749521',
    projectId: 'codehub-bc560',
    storageBucket: 'codehub-bc560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjBwrDUVDzB3naOEMBXQfzdlGW2OOnLY',
    appId: '1:631248749521:ios:41d59d40f3c794ac6396f0',
    messagingSenderId: '631248749521',
    projectId: 'codehub-bc560',
    storageBucket: 'codehub-bc560.appspot.com',
    iosClientId:
        '631248749521-uikn093lep2fkq1eh17j5r875k1an0h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.codehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjBwrDUVDzB3naOEMBXQfzdlGW2OOnLY',
    appId: '1:631248749521:ios:41d59d40f3c794ac6396f0',
    messagingSenderId: '631248749521',
    projectId: 'codehub-bc560',
    storageBucket: 'codehub-bc560.appspot.com',
    iosClientId:
        '631248749521-uikn093lep2fkq1eh17j5r875k1an0h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.codehub',
  );
}
